name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: 'Debug Fly connection'
      run: "curl -H 'flyio-debug: doit' -v https://debug.fly.dev"
    - name: 'Debug Fly registry connection'
      run: "curl -H 'flyio-debug: doit' -v https://registry.fly.io"
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
        limit-access-to-users: pborzenkov
